import type { PlatformGenerator } from '../types.js';
import type { GeneratorContext, GeneratorResult, GeneratedFile } from '../../types.js';

export class CursorGenerator implements PlatformGenerator {
  readonly platform = 'cursor';

  async generate(ctx: GeneratorContext): Promise<GeneratorResult> {
    const files: GeneratedFile[] = [];
    const warnings: string[] = [];
    const { skill } = ctx;
    const cursorOverrides = skill.extensions.platforms?.cursor;

    files.push({
      path: '.cursor-plugin/plugin.json',
      content: JSON.stringify(buildPluginManifest(skill.name, skill.description), null, 2),
    });

    files.push({
      path: `.cursor/skills/${slugify(skill.name)}/SKILL.md`,
      content: buildCursorSkillMd(ctx),
    });

    if (ctx.resolvedTools.length > 0) {
      files.push({
        path: 'mcp.json',
        content: JSON.stringify(buildMcpJson(skill.name), null, 2),
      });
    }

    if (cursorOverrides?.rules) {
      for (const rule of cursorOverrides.rules) {
        files.push({
          path: `.cursor/rules/${rule}`,
          content: `# ${rule}\n\n<!-- Auto-generated by elastic-skill-compiler. Populate with rule content. -->\n`,
        });
      }
    }

    if (cursorOverrides?.commands) {
      for (const cmd of cursorOverrides.commands) {
        files.push({
          path: `.cursor/commands/${slugify(cmd.name)}.md`,
          content: buildCommandFile(cmd.name, cmd.description),
        });
      }
    }

    if (cursorOverrides?.agents) {
      for (const agent of cursorOverrides.agents) {
        files.push({
          path: `.cursor/agents/${agent.file}`,
          content: `# ${agent.name}\n\n<!-- Auto-generated agent stub -->\n`,
        });
      }
    }

    return { platform: 'cursor', files, warnings };
  }
}

function buildPluginManifest(name: string, description: string) {
  return {
    name: slugify(name),
    displayName: name,
    description,
    version: '0.1.0',
    skills: [`.cursor/skills/${slugify(name)}/SKILL.md`],
    mcp: 'mcp.json',
  };
}

function buildCursorSkillMd(ctx: GeneratorContext): string {
  const { skill } = ctx;
  const lines: string[] = [];

  lines.push('---');
  lines.push(`name: ${skill.name}`);
  lines.push(`description: ${skill.description}`);
  if (skill.frontmatter.license) {
    lines.push(`license: ${skill.frontmatter.license}`);
  }
  lines.push('---');
  lines.push('');
  lines.push(skill.content);

  const platformExtra = skill.platformOverrides.get('cursor');
  if (platformExtra) {
    lines.push('');
    lines.push(platformExtra);
  }

  if (ctx.resolvedTools.length > 0) {
    lines.push('');
    lines.push('## Available Tools');
    lines.push('');
    for (const tool of ctx.resolvedTools) {
      lines.push(`### \`${tool.name}\``);
      lines.push(tool.description);
      lines.push('');
      if (tool.parameters.length > 0) {
        lines.push('**Parameters:**');
        for (const param of tool.parameters) {
          const req = param.required !== false ? '(required)' : '(optional)';
          lines.push(`- \`${param.name}\` (${param.type}) ${req}: ${param.description}`);
        }
        lines.push('');
      }
    }
  }

  return lines.join('\n');
}

function buildMcpJson(skillName: string) {
  return {
    mcpServers: {
      [slugify(skillName)]: {
        command: 'node',
        args: ['dist/mcp-server.js'],
        env: {},
      },
    },
  };
}

function buildCommandFile(name: string, description: string): string {
  return `---\ndescription: ${description}\n---\n\n# ${name}\n\n<!-- Implement command logic -->\n`;
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}
